### ISSUE TITLE
Confusing LICENSE.md

### ISSUE THREAD

**Issue by tniessen** [nodejs/performance#6]
- What content is being licensed?
- Who made the decision that the license should be MIT?
- The copyright holder `Node.js Foundation` does not exist anymore.

**Comment by anonrig** [comment]
Hi @tniessen

This was one of meeting topics, about what information we should put into the performance repository. Would you like to join today's meeting? https://github.com/nodejs/performance/issues/7

**Comment by anonrig** [comment]
Today's meeting was not available on Youtube. Therefore, I feel like I should answer your question here. I was copying the information from `security-wg` repository to create a base, and I realized that we should first discuss this before I pushed it on the repository. Unfortunately, while pushing the README, I also pushed the LICENSE too. That's why the LICENSE is there and has `Node.js Foundation`. 

I created a pull request to remove this, and updated README with more information regarding the governance model. Appreciate any feedback! 👍
